/* =====================================================================
 * coords.js — the geocaching bit.
 *
 * The final coordinates are NEVER stored in this repository as plain
 * text. They are stored as ten masked digits. The mask is a keystream
 * derived from the three "seals" the player earns by finishing all
 * three date routes at GOLD rank.
 *
 * The mask is digit-wise addition modulo 10, which has a deliberate and
 * rather pleasant property: *every* key produces well-formed, plausible
 * coordinates. Someone who skims the source and guesses at the key gets
 * a perfectly valid-looking set of coordinates that is simply wrong,
 * with no way to tell it apart from the real one. Play the game.
 *
 * CACHE OWNERS: do not edit the digits by hand. Open tools/setup.html,
 * type your real final coordinates, and paste the generated config
 * block over CACHE_CONFIG below. See README.md.
 * ===================================================================== */
"use strict";

window.GEO = (function () {
  /* ------------------------------------------------------------------
   * CACHE OWNER CONFIG — generated by tools/setup.html
   * ------------------------------------------------------------------ */
  const CACHE_CONFIG = {
    /* Cache identity, shown on the reveal screen. */
    gcCode: "GC1LOVE",
    cacheName: "Liebe auf den ersten Log",
    owner: "Team Aperture",

    /* Listing (posted) coordinates — public, safe to show. */
    postedCoords: "N 50° 00.000 E 008° 00.000",

    /* Degrees of the FINAL are public; only the minutes are the puzzle.
     * Final reads:  N <latDeg>° AB.CDE   E <lonDeg>° FG.HIJ           */
    latHem: "N",
    latDeg: 50,
    lonHem: "E",
    lonDeg: 8,

    /* The ten secret digits A B C D E F G H I J, masked. Ten chars.
     * Ships with a demo final so a fresh clone is playable end to end. */
    cipher: "4738484021",

    /* Set false only if you genuinely want the coordinates in clear
     * text in the source (useful while testing your own build). */
    masked: true,

    /* Optional. Leave "" to hide the button. */
    checkerUrl: "",

    /* Optional hint, ROT13-encoded like a real listing hint. */
    hintRot13: "",

    /* Optional: metres of the final from the posted coordinates, so
     * solvers can sanity-check they are inside the 2 mile / 3.2 km
     * guideline radius. Set 0 to hide. */
    distanceFromPostedMeters: 0
  };

  /* ------------------------------------------------------------------
   * Seals. One per route, earned only at GOLD rank.
   *
   * The array holds decoys as well as the real thing. Which entries are
   * live is decided by the route table below, at runtime, from state
   * the player actually earned — so reading this list tells you very
   * little on its own.
   * ------------------------------------------------------------------ */
  const SEALS = [
    "PETLING-IM-REGEN",
    "NEODYM-AM-GELAENDER",
    "ROT13-IM-BROMBEERBUSCH",
    "TFTC-OHNE-STIFT",
    "DNF-MIT-WUERDE",
    "MUGGEL-MIT-HUND",
    "FTF-UM-VIER-UHR",
    "DOSE-IST-WEG"
  ];

  /* route id -> index into SEALS. */
  const SEAL_OF = { petra: 0, nando: 1, mysti: 2 };

  /* Which coordinate digits each route unlocks (0-based, A=0 .. J=9). */
  const SHARDS = {
    petra: [0, 1, 2, 3],
    nando: [4, 5, 6],
    mysti: [7, 8, 9]
  };

  const DIGIT_LABELS = ["A", "B", "C", "D", "E", "F", "G", "H", "I", "J"];

  /* ------------------------------------------------------------------
   * Deterministic keystream. Small on purpose: this is a mask, not a
   * vault, and it must produce identical output in the browser and in
   * tools/setup.html without any crypto API (the game has to work from
   * file:// on a phone in a forest with no signal).
   * ------------------------------------------------------------------ */
  function fnv1a(str) {
    let h = 0x811c9dc5;
    for (let i = 0; i < str.length; i++) {
      h ^= str.charCodeAt(i);
      h = Math.imul(h, 0x01000193) >>> 0;
    }
    return h >>> 0;
  }

  function keystream(key, length) {
    let s = fnv1a("liebe-auf-den-ersten-log::" + key) || 0x9e3779b9;
    const out = [];
    for (let i = 0; i < length; i++) {
      /* xorshift32 */
      s ^= s << 13; s >>>= 0;
      s ^= s >>> 17;
      s ^= s << 5;  s >>>= 0;
      out.push(s % 10);
    }
    return out;
  }

  const toDigits = (s) => String(s).split("").map((c) => parseInt(c, 10) || 0);

  /** Each route masks only its own slice, so shards can be revealed
   *  one date at a time instead of all at the end. */
  function shardKey(route) {
    return route + "::" + SEALS[SEAL_OF[route]];
  }

  function shiftGroup(digits, route, direction) {
    const idx = SHARDS[route];
    const ks = keystream(shardKey(route), idx.length);
    idx.forEach((pos, i) => {
      digits[pos] = (((digits[pos] + direction * ks[i]) % 10) + 10) % 10;
    });
  }

  function shiftAll(value, direction) {
    const digits = toDigits(String(value).padEnd(10, "0"));
    Object.keys(SHARDS).forEach((r) => shiftGroup(digits, r, direction));
    return digits.join("");
  }

  /** Mask plaintext digits for storage. Used by tools/setup.html. */
  function encode(plainDigits) { return shiftAll(plainDigits, +1); }

  /** Recover the ten real digits. */
  function decode(cipherDigits) { return shiftAll(cipherDigits, -1); }

  /* ------------------------------------------------------------------
   * Public API
   * ------------------------------------------------------------------ */

  const ROUTES = ["petra", "nando", "mysti"];

  function complete(goldRoutes) {
    return ROUTES.every((r) => goldRoutes.indexOf(r) !== -1);
  }

  /** All ten real digits. Only meaningful once every route is GOLD. */
  function digits(goldRoutes) {
    if (!complete(goldRoutes)) return null;
    return CACHE_CONFIG.masked ? decode(CACHE_CONFIG.cipher) : CACHE_CONFIG.cipher;
  }

  /**
   * Ten slots in coordinate order, each either a revealed digit or null.
   * A route that is not yet GOLD leaves its slots empty.
   */
  function slots(goldRoutes) {
    const real = CACHE_CONFIG.masked
      ? decode(CACHE_CONFIG.cipher)
      : String(CACHE_CONFIG.cipher).padEnd(10, "0");
    const owner = {};
    ROUTES.forEach((r) => SHARDS[r].forEach((i) => { owner[i] = r; }));
    return DIGIT_LABELS.map((label, i) => ({
      label: label,
      route: owner[i],
      value: goldRoutes.indexOf(owner[i]) !== -1 ? real[i] : null
    }));
  }

  /** Pad a degree value the way a GPSr does (N 50°, E 008°). */
  const padDeg = (n, width) => String(n).padStart(width, "0");

  function format(digits) {
    const d = String(digits).padEnd(10, "0");
    const lat =
      CACHE_CONFIG.latHem +
      " " + padDeg(CACHE_CONFIG.latDeg, 2) +
      "° " + d.slice(0, 2) + "." + d.slice(2, 5);
    const lon =
      CACHE_CONFIG.lonHem +
      " " + padDeg(CACHE_CONFIG.lonDeg, 3) +
      "° " + d.slice(5, 7) + "." + d.slice(7, 10);
    return { lat, lon, pretty: lat + " " + lon };
  }

  /** Decimal degrees, for map links. */
  function decimal(digits) {
    const d = String(digits).padEnd(10, "0");
    const latMin = parseFloat(d.slice(0, 2) + "." + d.slice(2, 5));
    const lonMin = parseFloat(d.slice(5, 7) + "." + d.slice(7, 10));
    let lat = CACHE_CONFIG.latDeg + latMin / 60;
    let lon = CACHE_CONFIG.lonDeg + lonMin / 60;
    if (CACHE_CONFIG.latHem === "S") lat = -lat;
    if (CACHE_CONFIG.lonHem === "W") lon = -lon;
    return { lat: lat.toFixed(6), lon: lon.toFixed(6) };
  }

  function links(digits) {
    const dd = decimal(digits);
    return {
      geo: "geo:" + dd.lat + "," + dd.lon,
      maps: "https://www.google.com/maps?q=" + dd.lat + "," + dd.lon,
      osm:
        "https://www.openstreetmap.org/?mlat=" + dd.lat +
        "&mlon=" + dd.lon + "#map=17/" + dd.lat + "/" + dd.lon
    };
  }

  /** Cross-sum of the ten digits — the classic self-check for solvers. */
  function checksum(digits) {
    return toDigits(digits).reduce((a, b) => a + b, 0);
  }

  function rot13(s) {
    return String(s).replace(/[a-zA-Z]/g, (c) => {
      const base = c <= "Z" ? 65 : 97;
      return String.fromCharCode(((c.charCodeAt(0) - base + 13) % 26) + base);
    });
  }

  /** Just the digits one route hands over, for the route-end screen. */
  function shardFor(route, goldRoutes) {
    const all = slots(goldRoutes);
    return SHARDS[route].map((i) => all[i]);
  }

  return {
    config: CACHE_CONFIG,
    ROUTES: ROUTES,
    SHARDS: SHARDS,
    DIGIT_LABELS: DIGIT_LABELS,
    encode: encode,
    decode: decode,
    complete: complete,
    digits: digits,
    slots: slots,
    shardFor: shardFor,
    format: format,
    decimal: decimal,
    links: links,
    checksum: checksum,
    rot13: rot13
  };
})();
